default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer

  - repo: local
    hooks:
      # NOTE: This is a total unnecessary check, just used as part of the
      #       template. Remove this after creating the template.
      - id: check-python
        name: check-python
        entry: python --version
        language: system
        pass_filenames: no

      - id: black
        name: black
        entry: black
        language: system
        pass_filenames: true
        types:
          - python

      - id: ruff
        name: ruff
        entry: ruff --fix
        language: system
        pass_filenames: true
        require_serial: yes
        files: "./"
        types:
          - python
